name: ASH

on:
  workflow_dispatch:
  push:
    branches:
    - ash
  pull_request:
    branches:
    - ash

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Automated Security Helper
        run: |
          git clone https://github.com/aws-samples/automated-security-helper.git /tmp/ash
          /tmp/ash/ash --source-dir .
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ash-report
          path: aggregated_results.txt