name: ASH

on:
  workflow_dispatch:
  push:
    branches:
    - ash
  pull_request:
    branches:
    - ash

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          git clone https://github.com/aws-samples/automated-security-helper.git /tmp/ash
      - name: ASH
        run: /tmp/ash/ash --source-dir .
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: /home/runner/work/aws-sdk-pandas/aws-sdk-pandas/aggregated_results.txt