name: ASH

on:
  workflow_dispatch:
  push:
    branches:
    - ash
  pull_request:
    branches:
    - ash

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Automated Security Helper
        run: |
          mkdir ash-report
          git clone https://github.com/aws-samples/automated-security-helper.git
          ./automated-security-helper/ash --source-dir . --output-dir ash-report
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ash-report
          path: ash-report